id: 0b6e9aade58b472d8295cf0f101c07ee
initial_creation_type: ocr
source_metadata:
  volumes:
    1c22f96684604ddd8bba4de5a0c6d661:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
